# Generated by Django 2.2 on 2019-04-28 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='仪器名称')),
                ('depict', models.TextField(blank=True, max_length=200, verbose_name='仪器描述')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='仪器图片')),
                ('startValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='状态值')),
                ('alertValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='阈值')),
                ('min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最小值')),
                ('max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最大值')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=10, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='生产时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仪器',
                'verbose_name_plural': '仪器',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别')),
                ('depict', models.TextField(blank=True, max_length=200, verbose_name='描述')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序')),
            ],
            options={
                'verbose_name': '仪器分类',
                'verbose_name_plural': '仪器分类',
            },
        ),
        migrations.CreateModel(
            name='Repaircord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_time', models.DateTimeField(auto_now_add=True, verbose_name='受理时间')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='维修成功时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='维修是否完成')),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair', to='appliance.Appliance', verbose_name='损坏仪器')),
            ],
            options={
                'verbose_name': '修理记录',
                'verbose_name_plural': '修理记录',
            },
        ),
    ]
