# Generated by Django 2.2 on 2019-04-28 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repaircord',
            name='sid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair', to=settings.AUTH_USER_MODEL, verbose_name='维修人员'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appliance.Category', verbose_name='分类'),
        ),
    ]
