# Generated by Django 2.2 on 2019-06-11 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliance', '0003_auto_20190603_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datacord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='状态值')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data', to='appliance.Appliance', verbose_name='损坏仪器')),
            ],
            options={
                'verbose_name': '修理记录',
                'verbose_name_plural': '修理记录',
            },
        ),
    ]
